[3] 12:31:45: Log started for 'C:\Data\GitRepo\ToscaRepoAutothon\Tosca_Autothon_Repo\Tosca_Autothon_Repo.tws'
[3] 12:31:45: Log level: 4
[3] 12:31:45: Release: 15.0.7.958
[3] 12:31:46: Tricentis.TCCore.Persistency.Repository.DbAccessException: Error while connecting to database! ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   --- End of inner exception stack trace ---
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Tricentis.TCCore.Persistency.Repository.ClusterRepository.Database.DbAdaptor.BeginTransaction(IsolationLevel isolationLevel)
   at Tricentis.TCCore.Persistency.Repository.ClusterRepository.Database.MSSQL.MSSQLAdaptor.BeginTransaction(IsolationLevel isolationLevel)
   --- End of inner exception stack trace ---
   at Tricentis.TCCore.Persistency.Repository.ClusterRepository.Database.MSSQL.MSSQLAdaptor.BeginTransaction(IsolationLevel isolationLevel)
   at Tricentis.TCCore.Persistency.Repository.ClusterRepository.ClusterRepository.IsRepositoryInitialized()
   at Tricentis.TCCore.Base.Workspace.InitializeForMultiUser(AbstractRepository localRepository, AbstractRepository commonRepository)
[1] 12:31:46: ShowErrorMessage 'title=Error : Open Workspace', message='Error while connecting to database!
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
The system cannot find the file specified
'
[3] 12:31:56: OpenWorkspace took 00:00:25.6693842 to finish
